import type * as React from "react";

export interface AppControllerBindingsPart1 {
  workspace: import("../../../lib/terminal-workbench").TerminalWorkspace;
  source: import("../../../lib/workspace-transport").WorkspaceSource;
  statusLabel: string;
  error: string | undefined;
  setWorkspaceState: React.Dispatch<React.SetStateAction<import("../../../lib/workspace-transport").WorkspaceLoadResult>>;
  runHistory: import("../../../lib/terminal-workbench").ResearchRunAudit[];
  setRunHistoryState: React.Dispatch<React.SetStateAction<import("../../../lib/research-run-transport").ResearchRunHistoryResult>>;
  strategyExperimentHistory: import("../../../lib/terminal-workbench").StrategyExperimentListItem[];
  setStrategyExperimentHistory: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyExperimentListItem[]>>;
  strategyExperimentHistorySourceKey: string | null;
  setStrategyExperimentHistorySourceKey: React.Dispatch<React.SetStateAction<string | null>>;
  strategyExperimentActive: import("../../../lib/terminal-workbench").StrategyExperimentDetail | null;
  setStrategyExperimentActive: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyExperimentDetail | null>>;
  strategyExperimentDimensions: import("../../../lib/terminal-workbench").StrategyExperimentDimension[];
  setStrategyExperimentDimensions: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyExperimentDimension[]>>;
  strategyExperimentDraftSourceKey: string | null;
  setStrategyExperimentDraftSourceKey: React.Dispatch<React.SetStateAction<string | null>>;
  strategyExperimentGuardrails: import("../../../lib/terminal-workbench").StrategyExperimentGuardrails;
  setStrategyExperimentGuardrails: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyExperimentGuardrails>>;
  strategyExperimentWalkForward: import("../../../lib/terminal-workbench").StrategyExperimentWalkForward | null;
  setStrategyExperimentWalkForward: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyExperimentWalkForward | null>>;
  isStrategyExperimentRunning: boolean;
  setIsStrategyExperimentRunning: React.Dispatch<React.SetStateAction<boolean>>;
  strategyExperimentError: string | null;
  setStrategyExperimentError: React.Dispatch<React.SetStateAction<string | null>>;
  aiReviewStage3Providers: import("../../../lib/ai-review-stage3").AiReviewProviderStatus[];
  setAiReviewStage3Providers: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AiReviewProviderStatus[]>>;
  aiReviewStage3ProviderId: import("../../../lib/ai-review-stage3").AiReviewProviderId;
  setAiReviewStage3ProviderId: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AiReviewProviderId>>;
  aiReviewStage3ExternalDataApproved: boolean;
  setAiReviewStage3ExternalDataApproved: React.Dispatch<React.SetStateAction<boolean>>;
  aiReviewStage3PrimaryExperimentId: string | null;
  setAiReviewStage3PrimaryExperimentId: React.Dispatch<React.SetStateAction<string | null>>;
  aiReviewStage3ComparisonExperimentIds: string[];
  setAiReviewStage3ComparisonExperimentIds: React.Dispatch<React.SetStateAction<string[]>>;
  aiReviewStage3CurrentReview: import("../../../lib/ai-review-stage3").AuthoritativeAiReviewRun | null;
  setAiReviewStage3CurrentReview: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AuthoritativeAiReviewRun | null>>;
  aiReviewStage3Decisions: import("../../../lib/ai-review-stage3").AiReviewDecision[];
  setAiReviewStage3Decisions: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AiReviewDecision[]>>;
  aiReviewStage3History: import("../../../lib/ai-review-stage3").AuthoritativeAiReviewRun[];
  setAiReviewStage3History: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AuthoritativeAiReviewRun[]>>;
  aiReviewStage3LegacyHistory: import("../../../lib/ai-review-stage3").LegacyAiReviewHistoryRecord[];
  setAiReviewStage3LegacyHistory: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").LegacyAiReviewHistoryRecord[]>>;
  aiReviewStage3DecisionDraft: import("../../../lib/ai-review-stage3").AppendAiReviewDecisionRequest;
  setAiReviewStage3DecisionDraft: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AppendAiReviewDecisionRequest>>;
  isLoadingAiReviewStage3: boolean;
  setIsLoadingAiReviewStage3: React.Dispatch<React.SetStateAction<boolean>>;
  isRunningAiReviewStage3: boolean;
  setIsRunningAiReviewStage3: React.Dispatch<React.SetStateAction<boolean>>;
  isAppendingAiReviewStage3Decision: boolean;
  setIsAppendingAiReviewStage3Decision: React.Dispatch<React.SetStateAction<boolean>>;
  aiReviewStage3Error: string | null;
  setAiReviewStage3Error: React.Dispatch<React.SetStateAction<string | null>>;
  strategyLibraryState: import("../../../lib/strategy-transport").StrategyLibraryResult;
  setStrategyLibraryState: React.Dispatch<React.SetStateAction<import("../../../lib/strategy-transport").StrategyLibraryResult>>;
  strategyProductionBindingState: import("../../../lib/strategy-transport").StrategyProductionBindingResult;
  setStrategyProductionBindingState: React.Dispatch<React.SetStateAction<import("../../../lib/strategy-transport").StrategyProductionBindingResult>>;
  productionStrategyHandoffState: import("../../../lib/strategy-transport").ProductionStrategyHandoffResult;
  setProductionStrategyHandoffState: React.Dispatch<React.SetStateAction<import("../../../lib/strategy-transport").ProductionStrategyHandoffResult>>;
  bindingStrategyRevision: string | null;
  setBindingStrategyRevision: React.Dispatch<React.SetStateAction<string | null>>;
  strategyValidationState: import("../../../lib/strategy-transport").StrategyValidationResult;
  setStrategyValidationState: React.Dispatch<React.SetStateAction<import("../../../lib/strategy-transport").StrategyValidationResult>>;
  researchNoteState: import("../../../lib/research-ai-transport").ResearchNoteResult;
  setResearchNoteState: React.Dispatch<React.SetStateAction<import("../../../lib/research-ai-transport").ResearchNoteResult>>;
  handoffNotesState: import("../../../lib/handoff-note-transport").HandoffNotesResult;
  setHandoffNotesState: React.Dispatch<React.SetStateAction<import("../../../lib/handoff-note-transport").HandoffNotesResult>>;
  settingsStatus: import("../../../lib/platform-settings").PlatformSettingsResult;
  setSettingsStatus: React.Dispatch<React.SetStateAction<import("../../../lib/platform-settings").PlatformSettingsResult>>;
  hasLoadedSettingsStatus: boolean;
  setHasLoadedSettingsStatus: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingSettingsConfiguration: boolean;
  setIsSavingSettingsConfiguration: React.Dispatch<React.SetStateAction<boolean>>;
  isTestingMonitoringWebhook: boolean;
  setIsTestingMonitoringWebhook: React.Dispatch<React.SetStateAction<boolean>>;
  installingDataDependency: import("../../../lib/platform-settings").InstallablePlatformDataDependency | null;
  setInstallingDataDependency: React.Dispatch<React.SetStateAction<import("../../../lib/platform-settings").InstallablePlatformDataDependency | null>>;
  settingsConfigurationMessage: string | null;
  setSettingsConfigurationMessage: React.Dispatch<React.SetStateAction<string | null>>;
  executionAdapterLedger: import("../../../lib/execution-adapter-ledger-transport").ExecutionAdapterLedgerResult;
  setExecutionAdapterLedger: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-ledger-transport").ExecutionAdapterLedgerResult>>;
  executionAdapterHealthProbe: import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterHealthProbeLoadResult;
  setExecutionAdapterHealthProbe: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterHealthProbeLoadResult>>;
  isRefreshingAdapterHealthProbe: boolean;
  setIsRefreshingAdapterHealthProbe: React.Dispatch<React.SetStateAction<boolean>>;
  executionAdapterCertifications: import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterCertificationRun[];
  setExecutionAdapterCertifications: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterCertificationRun[]>>;
  executionAdapterCertificationApplies: import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterCertificationApplyResult[];
  setExecutionAdapterCertificationApplies: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterCertificationApplyResult[]>>;
  executionAdapterControlledRestartEvidence: import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterControlledRestartEvidenceResult[];
  setExecutionAdapterControlledRestartEvidence: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterControlledRestartEvidenceResult[]>>;
  executionAdapterRestartAcceptances: import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterRestartAcceptanceResult[];
  setExecutionAdapterRestartAcceptances: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-certification-transport").ExecutionAdapterRestartAcceptanceResult[]>>;
  executionAdapterEnvironmentBindings: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterEnvironmentBindingResult[];
  setExecutionAdapterEnvironmentBindings: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterEnvironmentBindingResult[]>>;
  executionAdapterSecretMaterializations: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretMaterializationResult[];
  setExecutionAdapterSecretMaterializations: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretMaterializationResult[]>>;
  executionAdapterSecretManifestValidations: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretManifestValidationResult[];
  setExecutionAdapterSecretManifestValidations: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretManifestValidationResult[]>>;
  executionAdapterSecretReferences: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretReferenceResult[];
  setExecutionAdapterSecretReferences: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterSecretReferenceResult[]>>;
  executionAdapterRuntimeReloadPlans: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadPlanResult[];
  setExecutionAdapterRuntimeReloadPlans: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadPlanResult[]>>;
  executionAdapterRuntimeReloadExecutions: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadExecutionResult[];
  setExecutionAdapterRuntimeReloadExecutions: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadExecutionResult[]>>;
  executionAdapterRuntimeReloadAcceptances: import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadAcceptanceResult[];
  setExecutionAdapterRuntimeReloadAcceptances: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-secret-runtime-transport").ExecutionAdapterRuntimeReloadAcceptanceResult[]>>;
  executionAdapterOrchestrationDryRuns: import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterOrchestrationDryRunResult[];
  setExecutionAdapterOrchestrationDryRuns: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterOrchestrationDryRunResult[]>>;
  executionAdapterOrchestrationExecutions: import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterOrchestrationExecutionResult[];
  setExecutionAdapterOrchestrationExecutions: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterOrchestrationExecutionResult[]>>;
  executionAdapterHumanConfirmations: import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterHumanConfirmationResult[];
  setExecutionAdapterHumanConfirmations: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterHumanConfirmationResult[]>>;
  executionAdapterSandboxProbePlans: import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterSandboxProbePlanResult[];
  setExecutionAdapterSandboxProbePlans: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-orchestration-transport").ExecutionAdapterSandboxProbePlanResult[]>>;
  executionAdapterSandboxProbeExecutions: import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterSandboxProbeExecutionResult[];
  setExecutionAdapterSandboxProbeExecutions: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterSandboxProbeExecutionResult[]>>;
  executionAdapterSandboxProbeReviews: import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterSandboxProbeReviewResult[];
  setExecutionAdapterSandboxProbeReviews: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterSandboxProbeReviewResult[]>>;
  executionAdapterSandboxOrderSchemaDryRuns: import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterSandboxOrderSchemaDryRunResult[];
  setExecutionAdapterSandboxOrderSchemaDryRuns: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterSandboxOrderSchemaDryRunResult[]>>;
  executionAdapterPaperOrderLifecycles: import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperOrderLifecycleResult[];
  setExecutionAdapterPaperOrderLifecycles: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperOrderLifecycleResult[]>>;
  executionAdapterPaperRouteRunbooks: import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperRouteRunbookResult[];
  setExecutionAdapterPaperRouteRunbooks: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperRouteRunbookResult[]>>;
  executionAdapterOpsStates: import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterOpsStateResult[];
  setExecutionAdapterOpsStates: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterOpsStateResult[]>>;
  executionAdapterPaperExecutions: import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperExecutionResult[];
  setExecutionAdapterPaperExecutions: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-paper-validation-transport").ExecutionAdapterPaperExecutionResult[]>>;
  executionAdapterProductionRouteReviews: import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterProductionRouteReviewResult[];
  setExecutionAdapterProductionRouteReviews: React.Dispatch<React.SetStateAction<import("../../../lib/execution-adapter-probe-transport").ExecutionAdapterProductionRouteReviewResult[]>>;
  adapterCertificationApplyConfirmations: Record<string, import("../../../lib/terminal-workbench").ExecutionAdapterCertificationApplyConfirmations>;
  setAdapterCertificationApplyConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../lib/terminal-workbench").ExecutionAdapterCertificationApplyConfirmations>>>;
  adapterRuntimeReloadAcceptanceConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterRuntimeReloadAcceptanceConfirmations>;
  setAdapterRuntimeReloadAcceptanceConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterRuntimeReloadAcceptanceConfirmations>>>;
  adapterOrchestrationDryRunConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOrchestrationDryRunConfirmations>;
  setAdapterOrchestrationDryRunConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOrchestrationDryRunConfirmations>>>;
  adapterOrchestrationExecutionConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOrchestrationExecutionConfirmations>;
  setAdapterOrchestrationExecutionConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOrchestrationExecutionConfirmations>>>;
  adapterHumanConfirmationConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterHumanConfirmationConfirmations>;
  setAdapterHumanConfirmationConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterHumanConfirmationConfirmations>>>;
  adapterSandboxProbePlanConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbePlanConfirmations>;
  setAdapterSandboxProbePlanConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbePlanConfirmations>>>;
  adapterSandboxProbeExecutionConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbeExecutionConfirmations>;
  setAdapterSandboxProbeExecutionConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbeExecutionConfirmations>>>;
  adapterSandboxProbeReviewConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbeReviewConfirmations>;
  setAdapterSandboxProbeReviewConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterSandboxProbeReviewConfirmations>>>;
  adapterProductionRouteReviewConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterProductionRouteReviewConfirmations>;
  setAdapterProductionRouteReviewConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterProductionRouteReviewConfirmations>>>;
  adapterOpsStateConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOpsStateConfirmations>;
  setAdapterOpsStateConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterOpsStateConfirmations>>>;
  adapterPaperExecutionConfirmations: Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterPaperExecutionConfirmations>;
  setAdapterPaperExecutionConfirmations: React.Dispatch<React.SetStateAction<Record<string, import("../../../pages/execution/ExecutionConfirmations").ExecutionAdapterPaperExecutionConfirmations>>>;
  auditSigningKeyRegistry: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRegistryResult;
  setAuditSigningKeyRegistry: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRegistryResult>>;
  auditSigningKeyRotationPlan: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationPlanResult;
  setAuditSigningKeyRotationPlan: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationPlanResult>>;
  auditSigningKeyRotationApply: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationApplyResult;
  setAuditSigningKeyRotationApply: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationApplyResult>>;
  auditSigningKeyRotationApplyConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRotationApplyConfirmations;
  setAuditSigningKeyRotationApplyConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRotationApplyConfirmations>>;
  auditSigningKeyRestartEvidence: import("../../../lib/audit-signing-key-transport").AuditSigningKeyControlledRestartEvidenceResult;
  setAuditSigningKeyRestartEvidence: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyControlledRestartEvidenceResult>>;
  auditSigningKeyRestartEvidenceConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRestartEvidenceConfirmations;
  setAuditSigningKeyRestartEvidenceConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRestartEvidenceConfirmations>>;
  auditSigningKeySecretMaterialization: import("../../../lib/audit-signing-key-transport").AuditSigningKeySecretMaterializationResult;
  setAuditSigningKeySecretMaterialization: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeySecretMaterializationResult>>;
  auditSigningKeySecretMaterializationConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeySecretMaterializationConfirmations;
  setAuditSigningKeySecretMaterializationConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeySecretMaterializationConfirmations>>;
  auditSigningKeyEnvironmentBinding: import("../../../lib/audit-signing-key-transport").AuditSigningKeyEnvironmentBindingResult;
  setAuditSigningKeyEnvironmentBinding: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyEnvironmentBindingResult>>;
  auditSigningKeyEnvironmentBindingConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyEnvironmentBindingConfirmations;
  setAuditSigningKeyEnvironmentBindingConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyEnvironmentBindingConfirmations>>;
  auditSigningKeyRuntimeReloadPlan: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRuntimeReloadPlanResult;
  setAuditSigningKeyRuntimeReloadPlan: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRuntimeReloadPlanResult>>;
  auditSigningKeyRuntimeReloadPlanConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadPlanConfirmations;
  setAuditSigningKeyRuntimeReloadPlanConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadPlanConfirmations>>;
  auditSigningKeyRuntimeReloadExecution: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRuntimeReloadExecutionResult;
  setAuditSigningKeyRuntimeReloadExecution: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRuntimeReloadExecutionResult>>;
  auditSigningKeyRuntimeReloadExecutionConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadExecutionConfirmations;
  setAuditSigningKeyRuntimeReloadExecutionConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadExecutionConfirmations>>;
  auditSigningKeyRotationAcceptance: import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationAcceptanceResult;
  setAuditSigningKeyRotationAcceptance: React.Dispatch<React.SetStateAction<import("../../../lib/audit-signing-key-transport").AuditSigningKeyRotationAcceptanceResult>>;
  auditSigningKeyRotationAcceptanceConfirmations: import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRotationAcceptanceConfirmations;
  setAuditSigningKeyRotationAcceptanceConfirmations: React.Dispatch<React.SetStateAction<import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRotationAcceptanceConfirmations>>;
  auditSigningKeyRotationPlanEventId: string | null;
  setAuditSigningKeyRotationPlanEventId: React.Dispatch<React.SetStateAction<string | null>>;
  auditSigningKeyRotationApplyEventId: string | null;
  setAuditSigningKeyRotationApplyEventId: React.Dispatch<React.SetStateAction<string | null>>;
  auditSigningKeyRotationLedgerStatus: import("../../../pages/audit/AuditLedgerFormatters").AuditSigningKeyRotationLedgerStatus;
  setAuditSigningKeyRotationLedgerStatus: React.Dispatch<React.SetStateAction<import("../../../pages/audit/AuditLedgerFormatters").AuditSigningKeyRotationLedgerStatus>>;
  goldenPathState: import("../../../lib/golden-path-transport").GoldenPathStatusResult;
  setGoldenPathState: React.Dispatch<React.SetStateAction<import("../../../lib/golden-path-transport").GoldenPathStatusResult>>;
  isAutomatedTradingWorkflowRunning: boolean;
  setIsAutomatedTradingWorkflowRunning: React.Dispatch<React.SetStateAction<boolean>>;
  automatedTradingWorkflowStatus: string | null;
  setAutomatedTradingWorkflowStatus: React.Dispatch<React.SetStateAction<string | null>>;
  desktopReleaseLatestState: import("../../../lib/release-acceptance-transport").DesktopReleaseLatestResult;
  setDesktopReleaseLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").DesktopReleaseLatestResult>>;
  stage1BootstrapPreflightLatestState: import("../../../lib/release-acceptance-transport").Stage1BootstrapPreflightLatestResult;
  setStage1BootstrapPreflightLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").Stage1BootstrapPreflightLatestResult>>;
  stage1DailyUseLatestState: import("../../../lib/release-acceptance-transport").Stage1DailyUseLatestResult;
  setStage1DailyUseLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").Stage1DailyUseLatestResult>>;
  stage1P0DailyUseRefreshOutcome: import("../../../lib/terminal-workbench").Stage1P0DailyUseRefreshOutcome | null;
  setStage1P0DailyUseRefreshOutcome: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").Stage1P0DailyUseRefreshOutcome | null>>;
  p0AcceptanceLatestState: import("../../../lib/release-acceptance-transport").P0AcceptanceLatestResult;
  setP0AcceptanceLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P0AcceptanceLatestResult>>;
  p1AcceptanceLatestState: import("../../../lib/release-acceptance-transport").P1AcceptanceLatestResult;
  setP1AcceptanceLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P1AcceptanceLatestResult>>;
  p2PaperReplayLatestState: import("../../../lib/release-acceptance-transport").P2PaperReplayLatestResult;
  setP2PaperReplayLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P2PaperReplayLatestResult>>;
  p2PreLiveAcceptanceLatestState: import("../../../lib/release-acceptance-transport").P2PreLiveAcceptanceLatestResult;
  setP2PreLiveAcceptanceLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P2PreLiveAcceptanceLatestResult>>;
  p2ReadinessAcceptanceLatestState: import("../../../lib/release-acceptance-transport").P2ReadinessAcceptanceLatestResult;
  setP2ReadinessAcceptanceLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P2ReadinessAcceptanceLatestResult>>;
  p2ReadinessAcceptanceAuditEvent: import("../../../lib/terminal-api-contract").AuditEventRecord | null;
  setP2ReadinessAcceptanceAuditEvent: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord | null>>;
  p2ReadinessAcceptanceReviewAuditEvent: import("../../../lib/terminal-api-contract").AuditEventRecord | null;
  setP2ReadinessAcceptanceReviewAuditEvent: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord | null>>;
  p2ReadinessEvidenceCoverageReviewAuditEvent: import("../../../lib/terminal-api-contract").AuditEventRecord | null;
  setP2ReadinessEvidenceCoverageReviewAuditEvent: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord | null>>;
  p2ManifestChainPreflightLatestState: import("../../../lib/release-acceptance-transport").P2ManifestChainPreflightLatestResult;
  setP2ManifestChainPreflightLatestState: React.Dispatch<React.SetStateAction<import("../../../lib/release-acceptance-transport").P2ManifestChainPreflightLatestResult>>;
  p2ManifestChainPreflightAuditEvent: import("../../../lib/terminal-api-contract").AuditEventRecord | null;
  setP2ManifestChainPreflightAuditEvent: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord | null>>;
  p2ManifestChainPreflightReviewAuditEvent: import("../../../lib/terminal-api-contract").AuditEventRecord | null;
  setP2ManifestChainPreflightReviewAuditEvent: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord | null>>;
  portfolioBacktestState: import("../../../lib/portfolio-transport").PortfolioBacktestResult;
  setPortfolioBacktestState: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioBacktestResult>>;
  portfolioPaperOrderBatches: import("../../../lib/portfolio-transport").PortfolioPaperOrderBatch[];
  setPortfolioPaperOrderBatches: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioPaperOrderBatch[]>>;
  portfolioPaperOrderLifecycleEvents: import("../../../lib/portfolio-transport").PortfolioPaperOrderLifecycleEvent[];
  setPortfolioPaperOrderLifecycleEvents: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioPaperOrderLifecycleEvent[]>>;
  portfolioPaperOrderSimulations: import("../../../lib/portfolio-transport").PortfolioPaperOrderSimulation[];
  setPortfolioPaperOrderSimulations: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioPaperOrderSimulation[]>>;
  portfolioPaperOrderReplay: import("../../../lib/portfolio-transport").PortfolioPaperOrderReplay | null;
  setPortfolioPaperOrderReplay: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioPaperOrderReplay | null>>;
  portfolioRouteRiskTemplate: import("../../../lib/terminal-workbench").PortfolioPaperOrderRouteRiskTemplate;
  setPortfolioRouteRiskTemplate: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").PortfolioPaperOrderRouteRiskTemplate>>;
  portfolioPaperOrderStateHistories: import("../../../lib/portfolio-transport").PortfolioPaperOrderStateHistory[];
  setPortfolioPaperOrderStateHistories: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-transport").PortfolioPaperOrderStateHistory[]>>;
  portfolioPaperOrderHistoryError: string | null;
  setPortfolioPaperOrderHistoryError: React.Dispatch<React.SetStateAction<string | null>>;
  portfolioStage4Workflows: import("../../../lib/portfolio-stage4").Stage4PortfolioWorkflow[];
  setPortfolioStage4Workflows: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-stage4").Stage4PortfolioWorkflow[]>>;
  portfolioRiskAssessments: import("../../../lib/portfolio-m5").PortfolioRiskAssessment[];
  setPortfolioRiskAssessments: React.Dispatch<React.SetStateAction<import("../../../lib/portfolio-m5").PortfolioRiskAssessment[]>>;
  portfolioRiskAssessmentError: string | null;
  setPortfolioRiskAssessmentError: React.Dispatch<React.SetStateAction<string | null>>;
  isRunningPortfolioRiskAssessment: boolean;
  setIsRunningPortfolioRiskAssessment: React.Dispatch<React.SetStateAction<boolean>>;
  autoTradingSnapshot: import("../../../pages/shared/auto-trading-contract").AutoTradingSnapshot | null;
  setAutoTradingSnapshot: React.Dispatch<React.SetStateAction<import("../../../pages/shared/auto-trading-contract").AutoTradingSnapshot | null>>;
  portfolioProductionRiskError: string | null;
  setPortfolioProductionRiskError: React.Dispatch<React.SetStateAction<string | null>>;
  isLoadingPortfolioProductionRisk: boolean;
  setIsLoadingPortfolioProductionRisk: React.Dispatch<React.SetStateAction<boolean>>;
  portfolioStage4RefreshGeneration: number;
  setPortfolioStage4RefreshGeneration: React.Dispatch<React.SetStateAction<number>>;
  stage5ShadowSessions: import("../../../lib/stage5-shadow").Stage5ShadowSession[];
  setStage5ShadowSessions: React.Dispatch<React.SetStateAction<import("../../../lib/stage5-shadow").Stage5ShadowSession[]>>;
  stage5SandboxReadinessDecisions: import("../../../lib/stage5-shadow").Stage5SandboxReadinessDecision[];
  setStage5SandboxReadinessDecisions: React.Dispatch<React.SetStateAction<import("../../../lib/stage5-shadow").Stage5SandboxReadinessDecision[]>>;
  stage5SandboxAuthorizationPreflights: import("../../../lib/stage5-shadow").Stage5SandboxAuthorizationPreflight[];
  setStage5SandboxAuthorizationPreflights: React.Dispatch<React.SetStateAction<import("../../../lib/stage5-shadow").Stage5SandboxAuthorizationPreflight[]>>;
  stage5SandboxAuthorizationReviews: import("../../../lib/stage5-shadow").Stage5SandboxAuthorizationReview[];
  setStage5SandboxAuthorizationReviews: React.Dispatch<React.SetStateAction<import("../../../lib/stage5-shadow").Stage5SandboxAuthorizationReview[]>>;
  stage5ExitAcceptance: import("../../../lib/stage5-shadow").Stage5ExitAcceptanceStatus | null;
  setStage5ExitAcceptance: React.Dispatch<React.SetStateAction<import("../../../lib/stage5-shadow").Stage5ExitAcceptanceStatus | null>>;
  stage5ExitAcceptanceError: string | null;
  setStage5ExitAcceptanceError: React.Dispatch<React.SetStateAction<string | null>>;
  stage5ShadowError: string | null;
  setStage5ShadowError: React.Dispatch<React.SetStateAction<string | null>>;
  stage6SandboxAuthorizations: import("../../../lib/stage6-sandbox").Stage6SandboxBatchAuthorization[];
  setStage6SandboxAuthorizations: React.Dispatch<React.SetStateAction<import("../../../lib/stage6-sandbox").Stage6SandboxBatchAuthorization[]>>;
  stage6SandboxBatch: import("../../../lib/stage6-sandbox").Stage6SandboxBatch | null;
  setStage6SandboxBatch: React.Dispatch<React.SetStateAction<import("../../../lib/stage6-sandbox").Stage6SandboxBatch | null>>;
  stage6ExitAcceptance: import("../../../lib/stage6-sandbox").Stage6ExitAcceptanceStatus | null;
  setStage6ExitAcceptance: React.Dispatch<React.SetStateAction<import("../../../lib/stage6-sandbox").Stage6ExitAcceptanceStatus | null>>;
  stage6KillSwitch: import("../../../lib/stage6-sandbox").Stage6KillSwitch | null;
  setStage6KillSwitchState: React.Dispatch<React.SetStateAction<import("../../../lib/stage6-sandbox").Stage6KillSwitch | null>>;
  stage6SandboxError: string | null;
  setStage6SandboxError: React.Dispatch<React.SetStateAction<string | null>>;
  isRunningStage6Sandbox: boolean;
  setIsRunningStage6Sandbox: React.Dispatch<React.SetStateAction<boolean>>;
  stage7ProductionReadonlyProbes: import("../../../lib/stage7-production-readonly").Stage7ProductionReadonlyProbe[];
  setStage7ProductionReadonlyProbes: React.Dispatch<React.SetStateAction<import("../../../lib/stage7-production-readonly").Stage7ProductionReadonlyProbe[]>>;
  stage7ProductionReadonlyError: string | null;
  setStage7ProductionReadonlyError: React.Dispatch<React.SetStateAction<string | null>>;
  isRunningStage7ProductionReadonly: boolean;
  setIsRunningStage7ProductionReadonly: React.Dispatch<React.SetStateAction<boolean>>;
  stage8ProductionReadonlyContinuity: import("../../../lib/stage8-readonly-continuity").Stage8ProductionReadonlyContinuity | null;
  setStage8ProductionReadonlyContinuity: React.Dispatch<React.SetStateAction<import("../../../lib/stage8-readonly-continuity").Stage8ProductionReadonlyContinuity | null>>;
  stage8ProductionReadonlyError: string | null;
  setStage8ProductionReadonlyError: React.Dispatch<React.SetStateAction<string | null>>;
  isUpdatingStage8ProductionReadonly: boolean;
  setIsUpdatingStage8ProductionReadonly: React.Dispatch<React.SetStateAction<boolean>>;
  stage9ProductionAdmissionCandidates: import("../../../lib/stage9-production-admission").Stage9ProductionAdmissionCandidate[];
  setStage9ProductionAdmissionCandidates: React.Dispatch<React.SetStateAction<import("../../../lib/stage9-production-admission").Stage9ProductionAdmissionCandidate[]>>;
  stage9ProductionAdmissionClock: number;
  setStage9ProductionAdmissionClock: React.Dispatch<React.SetStateAction<number>>;
  stage9ProductionAdmissionReviews: import("../../../lib/stage9-production-admission").Stage9ProductionAdmissionReview[];
  setStage9ProductionAdmissionReviews: React.Dispatch<React.SetStateAction<import("../../../lib/stage9-production-admission").Stage9ProductionAdmissionReview[]>>;
  stage9ProductionAdmissionError: string | null;
  setStage9ProductionAdmissionError: React.Dispatch<React.SetStateAction<string | null>>;
  isRunningStage9ProductionAdmission: boolean;
  setIsRunningStage9ProductionAdmission: React.Dispatch<React.SetStateAction<boolean>>;
  researchNoteDraft: string;
  setResearchNoteDraft: React.Dispatch<React.SetStateAction<string>>;
  researchNoteProviders: import("../../../lib/ai-review-stage3").AiReviewProviderStatus[];
  setResearchNoteProviders: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AiReviewProviderStatus[]>>;
  researchNoteProviderId: import("../../../lib/ai-review-stage3").AiReviewProviderId;
  setResearchNoteProviderId: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-stage3").AiReviewProviderId>>;
  researchNoteExternalDataApproved: boolean;
  setResearchNoteExternalDataApproved: React.Dispatch<React.SetStateAction<boolean>>;
  researchNoteGenerationError: string | null;
  setResearchNoteGenerationError: React.Dispatch<React.SetStateAction<string | null>>;
  researchNoteGenerationStatus: string | null;
  setResearchNoteGenerationStatus: React.Dispatch<React.SetStateAction<string | null>>;
  handoffNoteDraft: string;
  setHandoffNoteDraft: React.Dispatch<React.SetStateAction<string>>;
  klinesState: import("../../../lib/market-data-transport").MarketKlinesResult;
  setKlinesState: React.Dispatch<React.SetStateAction<import("../../../lib/market-data-transport").MarketKlinesResult>>;
  marketDataReadinessState: import("../../../lib/market-data-transport").MarketDataReadinessResult;
  setMarketDataReadinessState: React.Dispatch<React.SetStateAction<import("../../../lib/market-data-transport").MarketDataReadinessResult>>;
  marketCalendarState: import("../../../lib/market-data-transport").MarketCalendarResult;
  setMarketCalendarState: React.Dispatch<React.SetStateAction<import("../../../lib/market-data-transport").MarketCalendarResult>>;
  marketDiscoveryResult: import("../../../lib/market-exploration").MarketDiscoveryResult | null;
  setMarketDiscoveryResult: React.Dispatch<React.SetStateAction<import("../../../lib/market-exploration").MarketDiscoveryResult | null>>;
  isLoadingMarketDiscovery: boolean;
  setIsLoadingMarketDiscovery: React.Dispatch<React.SetStateAction<boolean>>;
  marketDiscoveryRequestIdRef: React.RefObject<number>;
  marketDiscoveryRequestMarketRef: React.RefObject<"ashare" | "crypto" | null>;
  marketAiSelection: import("../../../lib/market-ai-selection").MarketAiSelectionLoadResult;
  setMarketAiSelection: React.Dispatch<React.SetStateAction<import("../../../lib/market-ai-selection").MarketAiSelectionLoadResult>>;
  marketAiSelectionRequestKey: string | null;
  setMarketAiSelectionRequestKey: React.Dispatch<React.SetStateAction<string | null>>;
  isLoadingMarketAiSelection: boolean;
  setIsLoadingMarketAiSelection: React.Dispatch<React.SetStateAction<boolean>>;
  marketAiSelectionRequestRef: React.RefObject<import("../../../lib/latest-request").LatestRequestCoordinator>;
  marketAiSelectionReview: import("../../../lib/market-ai-selection").MarketAiSelectionReviewLoadResult;
  setMarketAiSelectionReview: React.Dispatch<React.SetStateAction<import("../../../lib/market-ai-selection").MarketAiSelectionReviewLoadResult>>;
  isLoadingMarketAiSelectionReview: boolean;
  setIsLoadingMarketAiSelectionReview: React.Dispatch<React.SetStateAction<boolean>>;
  marketAiSelectionReviewRequestRef: React.RefObject<import("../../../lib/latest-request").LatestRequestCoordinator>;
  marketAiSelectionStatistics: import("../../../lib/market-ai-selection").MarketAiSelectionQualityStatisticsLoadResult;
  setMarketAiSelectionStatistics: React.Dispatch<React.SetStateAction<import("../../../lib/market-ai-selection").MarketAiSelectionQualityStatisticsLoadResult>>;
  isLoadingMarketAiSelectionStatistics: boolean;
  setIsLoadingMarketAiSelectionStatistics: React.Dispatch<React.SetStateAction<boolean>>;
  marketAiSelectionStatisticsRequestRef: React.RefObject<import("../../../lib/latest-request").LatestRequestCoordinator>;
  pendingMarketAiSelectionResearchOrigin: (import("../../../lib/terminal-api-contract").MarketAiSelectionResearchOrigin & { market: import("../../../lib/terminal-workbench").Market; symbol: string; }) | null;
  setPendingMarketAiSelectionResearchOrigin: React.Dispatch<React.SetStateAction<(import("../../../lib/terminal-api-contract").MarketAiSelectionResearchOrigin & { market: import("../../../lib/terminal-workbench").Market; symbol: string; }) | null>>;
  marketInformationResult: import("../../../lib/market-exploration").MarketInformationResult | null;
  setMarketInformationResult: React.Dispatch<React.SetStateAction<import("../../../lib/market-exploration").MarketInformationResult | null>>;
  marketInformationNewsResult: import("../../../lib/market-exploration").MarketInformationResult | null;
  setMarketInformationNewsResult: React.Dispatch<React.SetStateAction<import("../../../lib/market-exploration").MarketInformationResult | null>>;
  marketInformationMarket: import("../../../lib/terminal-workbench").Market;
  setMarketInformationMarket: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").Market>>;
  isLoadingMarketInformation: boolean;
  setIsLoadingMarketInformation: React.Dispatch<React.SetStateAction<boolean>>;
}
