import type * as React from "react";

export interface AppControllerBindingsPart2 {
  isLoadingMarketInformationNews: boolean;
  setIsLoadingMarketInformationNews: React.Dispatch<React.SetStateAction<boolean>>;
  marketInformationRequestRef: React.RefObject<import("../../../lib/latest-request").LatestRequestCoordinator>;
  marketInformationNewsRequestRef: React.RefObject<import("../../../lib/latest-request").LatestRequestCoordinator>;
  marketInformationRequestContextRef: React.RefObject<string | null>;
  locale: import("../../../lib/i18n").Locale;
  setLocale: React.Dispatch<React.SetStateAction<import("../../../lib/i18n").Locale>>;
  colorSchemePreference: import("../../../lib/theme").ColorScheme | null;
  setColorSchemePreference: React.Dispatch<React.SetStateAction<import("../../../lib/theme").ColorScheme | null>>;
  textScale: number;
  setTextScale: React.Dispatch<React.SetStateAction<number>>;
  systemColorScheme: import("../../../lib/theme").ColorScheme;
  setSystemColorScheme: React.Dispatch<React.SetStateAction<import("../../../lib/theme").ColorScheme>>;
  colorScheme: import("../../../lib/theme").ColorScheme;
  initialWorkAreaSelection: import("../../../lib/terminal-workbench").ProductWorkAreaSelection;
  activeWorkAreaId: import("../../../lib/terminal-workbench").ProductWorkAreaId;
  setActiveWorkAreaId: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").ProductWorkAreaId>>;
  activeLoopStepId: string;
  setActiveLoopStepId: React.Dispatch<React.SetStateAction<string>>;
  activeWorkflowStageId: string;
  setActiveWorkflowStageId: React.Dispatch<React.SetStateAction<string>>;
  pendingStrategyGovernanceAction: import("../../../lib/terminal-workbench").StrategyGovernanceQueueRow | null;
  setPendingStrategyGovernanceAction: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").StrategyGovernanceQueueRow | null>>;
  workflowRunState: import("../../../lib/terminal-workbench").WorkflowRunState;
  setWorkflowRunState: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").WorkflowRunState>>;
  workflowStages: import("../../../lib/terminal-workbench").WorkflowStageView[];
  marketDraft: import("../../../lib/terminal-workbench").Market;
  setMarketDraft: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").Market>>;
  symbolDraft: string;
  setSymbolDraft: React.Dispatch<React.SetStateAction<string>>;
  searchSuggestions: import("../../../lib/market-exploration").MarketSearchSuggestion[];
  setSearchSuggestions: React.Dispatch<React.SetStateAction<import("../../../lib/market-exploration").MarketSearchSuggestion[]>>;
  isSearchOpen: boolean;
  setIsSearchOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isRefreshing: boolean;
  setIsRefreshing: React.Dispatch<React.SetStateAction<boolean>>;
  isRunning: boolean;
  setIsRunning: React.Dispatch<React.SetStateAction<boolean>>;
  isChartLoading: boolean;
  setIsChartLoading: React.Dispatch<React.SetStateAction<boolean>>;
  isSymbolSearching: boolean;
  setIsSymbolSearching: React.Dispatch<React.SetStateAction<boolean>>;
  hasUnsavedWatchlistChanges: boolean;
  setHasUnsavedWatchlistChanges: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingStrategy: boolean;
  setIsSavingStrategy: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingResearchNote: boolean;
  setIsSavingResearchNote: React.Dispatch<React.SetStateAction<boolean>>;
  isGeneratingResearchNoteDraft: boolean;
  setIsGeneratingResearchNoteDraft: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingHandoffNote: boolean;
  setIsSavingHandoffNote: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingWatchlist: boolean;
  setIsSavingWatchlist: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingResearchWorkspace: boolean;
  setIsSavingResearchWorkspace: React.Dispatch<React.SetStateAction<boolean>>;
  isRunningP0AiReview: boolean;
  setIsRunningP0AiReview: React.Dispatch<React.SetStateAction<boolean>>;
  isSubmittingPaperExecution: boolean;
  setIsSubmittingPaperExecution: React.Dispatch<React.SetStateAction<boolean>>;
  isRunningPortfolioBacktest: boolean;
  setIsRunningPortfolioBacktest: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingPortfolioPaperOrders: boolean;
  setIsRecordingPortfolioPaperOrders: React.Dispatch<React.SetStateAction<boolean>>;
  approvingPortfolioPaperOrderId: string | null;
  setApprovingPortfolioPaperOrderId: React.Dispatch<React.SetStateAction<string | null>>;
  simulatingPortfolioPaperOrderId: string | null;
  setSimulatingPortfolioPaperOrderId: React.Dispatch<React.SetStateAction<string | null>>;
  isSimulatingPortfolioPaperOrderBatch: boolean;
  setIsSimulatingPortfolioPaperOrderBatch: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingPortfolioStage4Workflow: boolean;
  setIsRecordingPortfolioStage4Workflow: React.Dispatch<React.SetStateAction<boolean>>;
  isRunningStage5Shadow: boolean;
  setIsRunningStage5Shadow: React.Dispatch<React.SetStateAction<boolean>>;
  isPreparingPortfolioPeers: boolean;
  setIsPreparingPortfolioPeers: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingDesktopRelease: boolean;
  setIsLoadingDesktopRelease: React.Dispatch<React.SetStateAction<boolean>>;
  isGeneratingStage1BootstrapPreflight: boolean;
  setIsGeneratingStage1BootstrapPreflight: React.Dispatch<React.SetStateAction<boolean>>;
  isGeneratingStage1DailyUse: boolean;
  setIsGeneratingStage1DailyUse: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP0Acceptance: boolean;
  setIsLoadingP0Acceptance: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP1Acceptance: boolean;
  setIsLoadingP1Acceptance: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP2PaperReplay: boolean;
  setIsLoadingP2PaperReplay: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP2PreLiveAcceptance: boolean;
  setIsLoadingP2PreLiveAcceptance: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP2ReadinessAcceptance: boolean;
  setIsLoadingP2ReadinessAcceptance: React.Dispatch<React.SetStateAction<boolean>>;
  isGeneratingP2ReadinessAcceptance: boolean;
  setIsGeneratingP2ReadinessAcceptance: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingP2ManifestChainPreflight: boolean;
  setIsLoadingP2ManifestChainPreflight: React.Dispatch<React.SetStateAction<boolean>>;
  isGeneratingP2ManifestChainPreflight: boolean;
  setIsGeneratingP2ManifestChainPreflight: React.Dispatch<React.SetStateAction<boolean>>;
  isSavingAiReviewRecord: boolean;
  setIsSavingAiReviewRecord: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingAiReviewHistory: boolean;
  setIsLoadingAiReviewHistory: React.Dispatch<React.SetStateAction<boolean>>;
  isInspectingExportPackage: boolean;
  setIsInspectingExportPackage: React.Dispatch<React.SetStateAction<boolean>>;
  isIndexingExportPackages: boolean;
  setIsIndexingExportPackages: React.Dispatch<React.SetStateAction<boolean>>;
  refreshingCacheKey: string | null;
  setRefreshingCacheKey: React.Dispatch<React.SetStateAction<string | null>>;
  marketDataRefreshOverride: import("../../../lib/terminal-workbench").MarketDataRefreshOverride | null;
  setMarketDataRefreshOverride: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").MarketDataRefreshOverride | null>>;
  marketDataRefreshOverrideAuditStatus: import("../../../components/ResearchContextReadinessPanel").MarketDataRefreshOverrideAuditStatus;
  setMarketDataRefreshOverrideAuditStatus: React.Dispatch<React.SetStateAction<import("../../../components/ResearchContextReadinessPanel").MarketDataRefreshOverrideAuditStatus>>;
  recordingAdapterCertificationId: string | null;
  setRecordingAdapterCertificationId: React.Dispatch<React.SetStateAction<string | null>>;
  applyingAdapterCertificationId: string | null;
  setApplyingAdapterCertificationId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterRuntimeReloadAcceptanceId: string | null;
  setRecordingAdapterRuntimeReloadAcceptanceId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterOrchestrationDryRunId: string | null;
  setRecordingAdapterOrchestrationDryRunId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterOrchestrationExecutionId: string | null;
  setRecordingAdapterOrchestrationExecutionId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterHumanConfirmationId: string | null;
  setRecordingAdapterHumanConfirmationId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterSandboxProbePlanId: string | null;
  setRecordingAdapterSandboxProbePlanId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterSandboxProbeExecutionId: string | null;
  setRecordingAdapterSandboxProbeExecutionId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterSandboxProbeReviewId: string | null;
  setRecordingAdapterSandboxProbeReviewId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterProductionRouteReviewId: string | null;
  setRecordingAdapterProductionRouteReviewId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterOpsStateId: string | null;
  setRecordingAdapterOpsStateId: React.Dispatch<React.SetStateAction<string | null>>;
  recordingAdapterPaperExecutionId: string | null;
  setRecordingAdapterPaperExecutionId: React.Dispatch<React.SetStateAction<string | null>>;
  isRefreshingWatchlistCache: boolean;
  setIsRefreshingWatchlistCache: React.Dispatch<React.SetStateAction<boolean>>;
  marketRefreshIssue: string | null;
  setMarketRefreshIssue: React.Dispatch<React.SetStateAction<string | null>>;
  watchlistCacheRefreshHistory: import("../../../lib/market-data-transport").CacheWatchlistRefreshRun[];
  setWatchlistCacheRefreshHistory: React.Dispatch<React.SetStateAction<import("../../../lib/market-data-transport").CacheWatchlistRefreshRun[]>>;
  selectedWatchlistCacheRefreshRunId: string | null;
  setSelectedWatchlistCacheRefreshRunId: React.Dispatch<React.SetStateAction<string | null>>;
  isChartExpanded: boolean;
  setIsChartExpanded: React.Dispatch<React.SetStateAction<boolean>>;
  isResearchPipelineConfirmationOpen: boolean;
  setIsResearchPipelineConfirmationOpen: React.Dispatch<React.SetStateAction<boolean>>;
  isLiveTradingGateDialogOpen: boolean;
  setIsLiveTradingGateDialogOpen: React.Dispatch<React.SetStateAction<boolean>>;
  hasUnsavedSettingsConfiguration: boolean;
  setHasUnsavedSettingsConfiguration: React.Dispatch<React.SetStateAction<boolean>>;
  pendingSettingsWorkAreaId: import("../../../lib/terminal-workbench").ProductWorkAreaId | null;
  setPendingSettingsWorkAreaId: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").ProductWorkAreaId | null>>;
  researchCompletionNotice: { dataRows: number; instrumentName: string; readbackReady: boolean; runId: string; symbol: string; timeframe: import("../../../lib/terminal-workbench").Timeframe; } | null;
  setResearchCompletionNotice: React.Dispatch<React.SetStateAction<{ dataRows: number; instrumentName: string; readbackReady: boolean; runId: string; symbol: string; timeframe: import("../../../lib/terminal-workbench").Timeframe; } | null>>;
  researchPipelineConfirmationDialogRef: React.RefObject<HTMLDialogElement | null>;
  researchPipelineConfirmationCancelButtonRef: React.RefObject<HTMLButtonElement | null>;
  liveTradingGateDialogRef: React.RefObject<HTMLDialogElement | null>;
  settingsUnsavedDialogRef: React.RefObject<HTMLDialogElement | null>;
  settingsUnsavedContinueButtonRef: React.RefObject<HTMLButtonElement | null>;
  pendingSettingsNavigationActionRef: React.RefObject<(() => void) | null>;
  settingsSaveRequestIdRef: React.RefObject<number>;
  paperExecutionRecord: import("../../../lib/paper-execution-transport").PaperExecutionRecord | null;
  setPaperExecutionRecord: React.Dispatch<React.SetStateAction<import("../../../lib/paper-execution-transport").PaperExecutionRecord | null>>;
  p0PaperSimulationRecord: import("../../../lib/p0-research-transport").P0PaperSimulationResponse | null;
  setP0PaperSimulationRecord: React.Dispatch<React.SetStateAction<import("../../../lib/p0-research-transport").P0PaperSimulationResponse | null>>;
  promotionCandidateRecord: import("../../../lib/paper-execution-transport").PromotionCandidateRecord | null;
  setPromotionCandidateRecord: React.Dispatch<React.SetStateAction<import("../../../lib/paper-execution-transport").PromotionCandidateRecord | null>>;
  aiReviewRunRecords: import("../../../lib/ai-review-run-transport").AiReviewRunRecordEnvelope[];
  setAiReviewRunRecords: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-run-transport").AiReviewRunRecordEnvelope[]>>;
  aiReviewArchivePreview: import("../../../pages/app-shell/initial-state").AiReviewArchivePreviewState;
  setAiReviewArchivePreview: React.Dispatch<React.SetStateAction<import("../../../pages/app-shell/initial-state").AiReviewArchivePreviewState>>;
  inspectedExportPackage: import("../../../lib/research-run-export-contract").ResearchRunExportPackage | null;
  setInspectedExportPackage: React.Dispatch<React.SetStateAction<import("../../../lib/research-run-export-contract").ResearchRunExportPackage | null>>;
  inspectedExportArchiveSnapshot: { aiReviewArchiveSnapshot: import("../../../lib/research-run-export-transport").AiReviewArchiveImportSnapshot; exportPackage: import("../../../lib/research-run-export-contract").ResearchRunExportPackage; runId: string; } | null;
  setInspectedExportArchiveSnapshot: React.Dispatch<React.SetStateAction<{ aiReviewArchiveSnapshot: import("../../../lib/research-run-export-transport").AiReviewArchiveImportSnapshot; exportPackage: import("../../../lib/research-run-export-contract").ResearchRunExportPackage; runId: string; } | null>>;
  pendingImportPackage: { aiReviewArchiveSnapshot: import("../../../lib/research-run-export-transport").AiReviewArchiveImportSnapshot; exportPackage: import("../../../lib/research-run-export-contract").ResearchRunExportPackage; fileName: string; } | null;
  setPendingImportPackage: React.Dispatch<React.SetStateAction<{ aiReviewArchiveSnapshot: import("../../../lib/research-run-export-transport").AiReviewArchiveImportSnapshot; exportPackage: import("../../../lib/research-run-export-contract").ResearchRunExportPackage; fileName: string; } | null>>;
  initialImportAuditEvidenceDeepLink: import("../../../pages/app-shell/url-state").InitialImportAuditEvidenceDeepLink | null;
  initialPaperExecutionDeepLink: import("../../../pages/app-shell/url-state").InitialPaperExecutionDeepLink | null;
  auditEvidenceReportEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setAuditEvidenceReportEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  executionAcceptanceAuditEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setExecutionAcceptanceAuditEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  marketDataRefreshOverrideAuditEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setMarketDataRefreshOverrideAuditEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  portfolioPaperOrderAuditEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setPortfolioPaperOrderAuditEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  executionAdapterPaperExecutionAuditEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setExecutionAdapterPaperExecutionAuditEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  auditSigningKeyRotationEvents: import("../../../lib/terminal-api-contract").AuditEventRecord[];
  setAuditSigningKeyRotationEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-api-contract").AuditEventRecord[]>>;
  auditEvidenceReportPagination: import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null;
  setAuditEvidenceReportPagination: React.Dispatch<React.SetStateAction<import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null>>;
  auditEvidenceReportQuery: string;
  setAuditEvidenceReportQuery: React.Dispatch<React.SetStateAction<string>>;
  auditEvidenceReportOffset: number;
  setAuditEvidenceReportOffset: React.Dispatch<React.SetStateAction<number>>;
  marketDataRefreshOverrideAuditPagination: import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null;
  setMarketDataRefreshOverrideAuditPagination: React.Dispatch<React.SetStateAction<import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null>>;
  marketDataRefreshOverrideAuditQuery: string;
  setMarketDataRefreshOverrideAuditQuery: React.Dispatch<React.SetStateAction<string>>;
  marketDataRefreshOverrideAuditOffset: number;
  setMarketDataRefreshOverrideAuditOffset: React.Dispatch<React.SetStateAction<number>>;
  portfolioPaperOrderAuditPagination: import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null;
  setPortfolioPaperOrderAuditPagination: React.Dispatch<React.SetStateAction<import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null>>;
  portfolioPaperOrderAuditQuery: string;
  setPortfolioPaperOrderAuditQuery: React.Dispatch<React.SetStateAction<string>>;
  portfolioPaperOrderAuditOffset: number;
  setPortfolioPaperOrderAuditOffset: React.Dispatch<React.SetStateAction<number>>;
  executionAdapterPaperExecutionAuditPagination: import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null;
  setExecutionAdapterPaperExecutionAuditPagination: React.Dispatch<React.SetStateAction<import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null>>;
  executionAdapterPaperExecutionAuditQuery: string;
  setExecutionAdapterPaperExecutionAuditQuery: React.Dispatch<React.SetStateAction<string>>;
  executionAdapterPaperExecutionAuditOffset: number;
  setExecutionAdapterPaperExecutionAuditOffset: React.Dispatch<React.SetStateAction<number>>;
  researchRunImportAuditEvents: import("../../../lib/terminal-workbench").ResearchRunImportAuditEvent[];
  setResearchRunImportAuditEvents: React.Dispatch<React.SetStateAction<import("../../../lib/terminal-workbench").ResearchRunImportAuditEvent[]>>;
  researchRunImportAuditPagination: import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null;
  setResearchRunImportAuditPagination: React.Dispatch<React.SetStateAction<import("../../../lib/audit-event-transport").AuditEventHistoryPagination | null>>;
  researchRunImportAuditQuery: string;
  setResearchRunImportAuditQuery: React.Dispatch<React.SetStateAction<string>>;
  researchRunImportAuditOffset: number;
  setResearchRunImportAuditOffset: React.Dispatch<React.SetStateAction<number>>;
  focusedAdapterPaperExecutionAuditEventId: string | null;
  setFocusedAdapterPaperExecutionAuditEventId: React.Dispatch<React.SetStateAction<string | null>>;
  focusedImportAuditEventId: string | null;
  setFocusedImportAuditEventId: React.Dispatch<React.SetStateAction<string | null>>;
  copiedImportAuditEvidenceEventId: string | null;
  setCopiedImportAuditEvidenceEventId: React.Dispatch<React.SetStateAction<string | null>>;
  copiedP0ActionOutcomeEvidenceId: string | null;
  setCopiedP0ActionOutcomeEvidenceId: React.Dispatch<React.SetStateAction<string | null>>;
  copiedP0AcceptanceReview: boolean;
  setCopiedP0AcceptanceReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedP2ReadinessAcceptanceReview: boolean;
  setCopiedP2ReadinessAcceptanceReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedP2ReadinessEvidenceCoverageReview: boolean;
  setCopiedP2ReadinessEvidenceCoverageReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedP2ManifestChainPreflightReview: boolean;
  setCopiedP2ManifestChainPreflightReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedPersonalTeamReadinessReview: boolean;
  setCopiedPersonalTeamReadinessReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedDailyOpsControlRoomReview: boolean;
  setCopiedDailyOpsControlRoomReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedDailyStartBriefReview: boolean;
  setCopiedDailyStartBriefReview: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUseHandoff: boolean;
  setCopiedStage1P0DailyUseHandoff: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUsePrimaryLink: boolean;
  setCopiedStage1P0DailyUsePrimaryLink: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0ShareLinkBundle: boolean;
  setCopiedStage1P0ShareLinkBundle: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUseArchive: boolean;
  setCopiedStage1P0DailyUseArchive: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUseStartupSnapshot: boolean;
  setCopiedStage1P0DailyUseStartupSnapshot: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0InvalidShareDiagnostics: boolean;
  setCopiedStage1P0InvalidShareDiagnostics: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUseRefreshOutcome: boolean;
  setCopiedStage1P0DailyUseRefreshOutcome: React.Dispatch<React.SetStateAction<boolean>>;
  copiedStage1P0DailyUseRefreshOutcomeLink: boolean;
  setCopiedStage1P0DailyUseRefreshOutcomeLink: React.Dispatch<React.SetStateAction<boolean>>;
  copiedP0ReadinessReport: boolean;
  setCopiedP0ReadinessReport: React.Dispatch<React.SetStateAction<boolean>>;
  copiedOperatorRunbook: boolean;
  setCopiedOperatorRunbook: React.Dispatch<React.SetStateAction<boolean>>;
  copiedPreLiveRunbook: boolean;
  setCopiedPreLiveRunbook: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingOperatorRunbook: boolean;
  setIsRecordingOperatorRunbook: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingPreLiveRunbook: boolean;
  setIsRecordingPreLiveRunbook: React.Dispatch<React.SetStateAction<boolean>>;
  savingP0ReadinessReport: boolean;
  setSavingP0ReadinessReport: React.Dispatch<React.SetStateAction<boolean>>;
  savingP0AcceptanceReview: boolean;
  setSavingP0AcceptanceReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingP2ReadinessAcceptanceReview: boolean;
  setSavingP2ReadinessAcceptanceReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingP2ReadinessEvidenceCoverageReview: boolean;
  setSavingP2ReadinessEvidenceCoverageReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingP2ManifestChainPreflightReview: boolean;
  setSavingP2ManifestChainPreflightReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingPersonalTeamReadinessReview: boolean;
  setSavingPersonalTeamReadinessReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingDailyOpsControlRoomReview: boolean;
  setSavingDailyOpsControlRoomReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingDailyStartBriefReview: boolean;
  setSavingDailyStartBriefReview: React.Dispatch<React.SetStateAction<boolean>>;
  savingStage1P0DailyUseArchive: boolean;
  setSavingStage1P0DailyUseArchive: React.Dispatch<React.SetStateAction<boolean>>;
  copiedAuditEvidenceSummary: boolean;
  setCopiedAuditEvidenceSummary: React.Dispatch<React.SetStateAction<boolean>>;
  copiedAuditEvidenceReport: boolean;
  setCopiedAuditEvidenceReport: React.Dispatch<React.SetStateAction<boolean>>;
  copiedResearchContextLink: boolean;
  setCopiedResearchContextLink: React.Dispatch<React.SetStateAction<boolean>>;
  copiedResearchContextReadinessReport: boolean;
  setCopiedResearchContextReadinessReport: React.Dispatch<React.SetStateAction<boolean>>;
  importAuditEvidenceDeepLinkStatus: import("../../../pages/app-shell/url-state").ImportAuditEvidenceDeepLinkStatus | null;
  setImportAuditEvidenceDeepLinkStatus: React.Dispatch<React.SetStateAction<import("../../../pages/app-shell/url-state").ImportAuditEvidenceDeepLinkStatus | null>>;
  paperExecutionDeepLinkStatus: import("../../../pages/app-shell/url-state").PaperExecutionDeepLinkStatus | null;
  setPaperExecutionDeepLinkStatus: React.Dispatch<React.SetStateAction<import("../../../pages/app-shell/url-state").PaperExecutionDeepLinkStatus | null>>;
  researchRunExportBrowserQuery: string;
  setResearchRunExportBrowserQuery: React.Dispatch<React.SetStateAction<string>>;
  researchRunImportDiffQuery: string;
  setResearchRunImportDiffQuery: React.Dispatch<React.SetStateAction<string>>;
  indexedExportPackages: import("../../../lib/research-run-export-contract").ResearchRunExportPackage[];
  setIndexedExportPackages: React.Dispatch<React.SetStateAction<import("../../../lib/research-run-export-contract").ResearchRunExportPackage[]>>;
  aiReviewHistoryPagination: import("../../../lib/ai-review-run-transport").AiReviewRunHistoryPagination | null;
  setAiReviewHistoryPagination: React.Dispatch<React.SetStateAction<import("../../../lib/ai-review-run-transport").AiReviewRunHistoryPagination | null>>;
  aiReviewHistoryQuery: string;
  setAiReviewHistoryQuery: React.Dispatch<React.SetStateAction<string>>;
  aiReviewHistoryOffset: number;
  setAiReviewHistoryOffset: React.Dispatch<React.SetStateAction<number>>;
  isApplyingImportPackage: boolean;
  setIsApplyingImportPackage: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingAuditEvidenceReportEvents: boolean;
  setIsLoadingAuditEvidenceReportEvents: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingMarketDataRefreshOverrideAudit: boolean;
  setIsLoadingMarketDataRefreshOverrideAudit: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingPortfolioPaperOrderAudit: boolean;
  setIsLoadingPortfolioPaperOrderAudit: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingExecutionAdapterPaperExecutionAudit: boolean;
  setIsLoadingExecutionAdapterPaperExecutionAudit: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingAuditSigningKeyRotationEvents: boolean;
  setIsLoadingAuditSigningKeyRotationEvents: React.Dispatch<React.SetStateAction<boolean>>;
  isLoadingResearchRunImportAudit: boolean;
  setIsLoadingResearchRunImportAudit: React.Dispatch<React.SetStateAction<boolean>>;
  isApplyingAuditSigningKeyRotationPlan: boolean;
  setIsApplyingAuditSigningKeyRotationPlan: React.Dispatch<React.SetStateAction<boolean>>;
  isPreparingAuditSigningKeyRotationPlan: boolean;
  setIsPreparingAuditSigningKeyRotationPlan: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeyRestartEvidence: boolean;
  setIsRecordingAuditSigningKeyRestartEvidence: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeySecretMaterialization: boolean;
  setIsRecordingAuditSigningKeySecretMaterialization: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeyEnvironmentBinding: boolean;
  setIsRecordingAuditSigningKeyEnvironmentBinding: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeyRuntimeReloadPlan: boolean;
  setIsRecordingAuditSigningKeyRuntimeReloadPlan: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeyRuntimeReloadExecution: boolean;
  setIsRecordingAuditSigningKeyRuntimeReloadExecution: React.Dispatch<React.SetStateAction<boolean>>;
  isRecordingAuditSigningKeyRotationAcceptance: boolean;
  setIsRecordingAuditSigningKeyRotationAcceptance: React.Dispatch<React.SetStateAction<boolean>>;
  signingAuditReportEventId: string | null;
  setSigningAuditReportEventId: React.Dispatch<React.SetStateAction<string | null>>;
  verifyingAuditReportEventId: string | null;
  setVerifyingAuditReportEventId: React.Dispatch<React.SetStateAction<string | null>>;
  revokingAuditReportEventId: string | null;
  setRevokingAuditReportEventId: React.Dispatch<React.SetStateAction<string | null>>;
  manualSelectionVersionRef: React.RefObject<number>;
  workspaceRef: React.RefObject<import("../../../lib/terminal-workbench").TerminalWorkspace>;
  researchNoteDraftRef: React.RefObject<string>;
  researchNoteDraftVersionRef: React.RefObject<number>;
  researchNoteDraftGenerationRequestIdRef: React.RefObject<number>;
  researchNoteDraftGenerationAbortControllerRef: React.RefObject<AbortController | null>;
  applyGeneratedResearchNoteDraft: (body: string) => void;
  updateResearchNoteDraft: (body: string) => void;
  editResearchNoteDraft: (body: string) => void;
}
