import type * as React from "react";

export interface AppControllerBindingsPart4 {
  updateAuditSigningKeyRuntimeReloadPlanConfirmation: (field: keyof import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadPlanConfirmations, value: boolean) => void;
  updateAuditSigningKeyRuntimeReloadExecutionConfirmation: (field: keyof import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRuntimeReloadExecutionConfirmations, value: boolean) => void;
  updateAuditSigningKeyRotationAcceptanceConfirmation: (field: keyof import("../../../pages/execution/ExecutionConfirmations").AuditSigningKeyRotationAcceptanceConfirmations, value: boolean) => void;
  prepareAuditSigningKeyRotationPlanForAudit: () => Promise<void>;
  recordAuditSigningKeySecretMaterializationForAudit: () => Promise<void>;
  saveSettingsConfiguration: (request: import("../../../lib/platform-settings").PlatformSettingsUpdateRequest) => Promise<boolean>;
  installSettingsDataDependency: (dependency: import("../../../lib/platform-settings").InstallablePlatformDataDependency) => Promise<void>;
  loadSettingsOpenAiCompatibleModels: (baseUrl: string) => Promise<import("../../../lib/platform-settings").OpenAiCompatibleModelsResult>;
  testSettingsMonitoringWebhook: () => Promise<void>;
  recordAuditSigningKeyEnvironmentBindingForAudit: () => Promise<void>;
  recordAuditSigningKeyRuntimeReloadPlanForAudit: () => Promise<void>;
  recordAuditSigningKeyRuntimeReloadExecutionForAudit: () => Promise<void>;
  recordAuditSigningKeyRotationAcceptanceForAudit: () => Promise<void>;
  applyAuditSigningKeyRotationPlanForAudit: () => Promise<void>;
  recordAuditSigningKeyRestartEvidenceForAudit: () => Promise<void>;
  refreshGoldenPathStatus: () => Promise<import("../../../lib/golden-path-transport").GoldenPathStatusResult>;
  refreshWorkspace: () => Promise<void>;
  refreshChart: (silent?: boolean) => Promise<void>;
  refreshVisiblePageData: () => Promise<void>;
  enableMarketDataRefreshOverride: (reason: string) => Promise<void>;
  clearMarketDataRefreshOverride: () => void;
  refreshCacheContext: (context: import("../../../lib/platform-settings").PlatformSettingsCacheContext) => Promise<boolean>;
  refreshSelectedMarketCache: () => Promise<boolean>;
  refreshWatchlistMarketCache: () => Promise<boolean>;
  loadHistoricalKlines: (beforeTimestampMs: number) => Promise<import("../../../lib/terminal-api-contract").MarketKlineBar[]>;
  runPipeline: (confirmation?: "accepted" | undefined) => Promise<boolean>;
  preparePortfolioPeerAudits: () => Promise<{ history: import("../../../lib/research-run-transport").ResearchRunHistoryResult | null; error: string; } | null>;
  runPortfolioBacktestDraft: () => Promise<void>;
  recordPortfolioPaperOrders: () => Promise<void>;
  reviewPortfolioPaperOrder: (row: import("../../../lib/terminal-workbench").PortfolioPaperOrderApprovalRow, approved: boolean) => Promise<void>;
  approvePortfolioPaperOrder: (row: import("../../../lib/terminal-workbench").PortfolioPaperOrderApprovalRow) => Promise<void>;
  rejectPortfolioPaperOrder: (row: import("../../../lib/terminal-workbench").PortfolioPaperOrderApprovalRow) => Promise<void>;
  updatePortfolioRouteRiskTemplate: (field: keyof import("../../../lib/terminal-workbench").PortfolioPaperOrderRouteRiskTemplate, value: number) => void;
  simulatePortfolioPaperOrder: (row: import("../../../lib/terminal-workbench").PortfolioPaperOrderApprovalRow) => Promise<void>;
  simulatePortfolioPaperOrderBatch: () => Promise<void>;
  recordPortfolioStage4Workflow: () => Promise<void>;
  runPortfolioRiskAssessment: (assessmentRequest: import("../../../lib/portfolio-m5").PortfolioRiskAssessmentRequest) => Promise<void>;
  runPortfolioStage4PrimaryAction: (actionId: string) => undefined;
  runStage5ShadowPrimaryAction: (reviewInput?: { outcome: "rejected" | "approved"; reason: string; } | undefined) => Promise<void>;
  runStage6SandboxAction: () => Promise<void>;
  runStage7ProductionReadonlyAction: (eligibilityConfirmed: boolean) => Promise<void>;
  runStage8ProductionReadonlyAccessAction: (action: "revoke" | "restore", reason: string) => Promise<void>;
  runStage9ProductionAdmissionCandidateAction: () => Promise<void>;
  runStage9ProductionAdmissionReviewAction: (reviewer: string, outcome: "rejected" | "approved", reason: string) => Promise<void>;
  runStage6KillSwitchAction: (triggered: boolean) => Promise<void>;
  exportPortfolioBacktestMarkdown: () => void;
  loadPaperExecutionDeepLink: (deepLink: import("../../../pages/app-shell/url-state").InitialPaperExecutionDeepLink) => Promise<void>;
  replayRun: (run: import("../../../lib/terminal-workbench").ResearchRunAudit) => Promise<boolean>;
  replayImportRollbackRun: (runId: string) => Promise<void>;
  ensureGoldenPathLatestRunBound: (latestRunIdOverride?: string | null | undefined) => Promise<boolean>;
  undoResearchRunImportEvent: (undoToken: string, expectedRunId: string) => Promise<void>;
  persistAuditEvidenceReportEvent: (auditReport: import("../../../lib/research-run-export-contract").ResearchRunExportAuditReport | undefined) => void;
  exportRun: (run: import("../../../lib/terminal-workbench").ResearchRunAudit) => Promise<void>;
  inspectRunExportPackageByRunId: (runId: string) => Promise<import("../../../pages/app-shell/initial-state").ResearchRunExportPackageInspectionResult>;
  copyResearchRunImportAuditEvidenceAnchor: (event: import("../../../lib/terminal-workbench").ResearchRunImportAuditEvent) => Promise<void>;
  copyAuditEvidenceSummary: () => Promise<void>;
  copyAuditEvidenceReport: () => Promise<void>;
  copyOperatorRunbook: () => Promise<void>;
  downloadOperatorRunbook: () => void;
  recordOperatorRunbook: () => Promise<void>;
  copyExecutionAdapterPreLiveRunbook: () => Promise<void>;
  downloadExecutionAdapterPreLiveRunbook: () => void;
  recordExecutionAdapterPreLiveRunbook: () => Promise<void>;
  copyResearchContextLink: () => Promise<void>;
  buildCurrentResearchContextReadinessReport: () => Promise<import("../../../lib/terminal-workbench").ResearchContextReadinessReportArchive>;
  copyResearchContextReadinessReport: () => Promise<void>;
  downloadResearchContextReadinessReport: () => Promise<void>;
  recordResearchContextReadinessReport: () => Promise<void>;
  downloadAuditEvidenceReport: () => Promise<void>;
  inspectRunExportPackage: (run: import("../../../lib/terminal-workbench").ResearchRunAudit) => Promise<void>;
  inspectResearchRunImportAuditEvent: (event: import("../../../lib/terminal-workbench").ResearchRunImportAuditEvent) => Promise<void>;
  loadImportAuditEvidenceDeepLink: (deepLink: import("../../../pages/app-shell/url-state").InitialImportAuditEvidenceDeepLink) => Promise<void>;
  retryImportAuditEvidenceDeepLink: () => void;
  indexRecentRunExportPackages: () => Promise<void>;
  exportBacktestReportMarkdown: () => void;
  exportAiReviewMarkdown: () => void;
  exportAiReviewRunRecord: () => void;
  saveCurrentAiReviewRunRecord: () => Promise<void>;
  appendResearchRunImportAuditEvent: (event: import("../../../lib/terminal-workbench").ResearchRunImportAuditEvent) => void;
  importRunExportFile: (event: React.ChangeEvent<HTMLInputElement, Element>) => Promise<void>;
  confirmPendingImportPackage: () => Promise<void>;
  cancelPendingImportPackage: () => void;
  updateAuditEvidenceReportQuery: (query: string) => void;
  previousAuditEvidenceReportPage: () => void;
  nextAuditEvidenceReportPage: () => void;
  updateMarketDataRefreshOverrideAuditQuery: (query: string) => void;
  previousMarketDataRefreshOverrideAuditPage: () => void;
  nextMarketDataRefreshOverrideAuditPage: () => void;
  updatePortfolioPaperOrderAuditQuery: (query: string) => void;
  previousPortfolioPaperOrderAuditPage: () => void;
  nextPortfolioPaperOrderAuditPage: () => void;
  updateExecutionAdapterPaperExecutionAuditQuery: (query: string) => void;
  previousExecutionAdapterPaperExecutionAuditPage: () => void;
  nextExecutionAdapterPaperExecutionAuditPage: () => void;
  signAuditEvidenceReportEvent: (eventId: string) => Promise<void>;
  verifyAuditEvidenceReportEvent: (eventId: string) => Promise<void>;
  revokeAuditEvidenceReportEvent: (eventId: string) => Promise<void>;
  updateResearchRunImportAuditQuery: (query: string) => void;
  runEvidencePackageControlAction: (row: import("../../../lib/terminal-workbench").EvidencePackageControlRoomRow) => void;
  previousResearchRunImportAuditPage: () => void;
  nextResearchRunImportAuditPage: () => void;
  updateAiReviewHistoryQuery: (query: string) => void;
  previousAiReviewHistoryPage: () => void;
  nextAiReviewHistoryPage: () => void;
  deferSettingsNavigation: (targetWorkAreaId: import("../../../lib/terminal-workbench").ProductWorkAreaId, navigationAction: () => void) => boolean;
  selectInstrument: (instrument: import("../../../lib/terminal-workbench").Instrument, targetWorkAreaId?: import("../../../lib/terminal-workbench").ProductWorkAreaId, addToWatchlist?: boolean) => void;
  researchMarketAiSelectionCandidate: (instrument: import("../../../lib/terminal-workbench").Instrument, origin: import("../../../lib/terminal-api-contract").MarketAiSelectionResearchOrigin) => void;
  selectWatchlistCacheRefreshItem: (row: import("../../../lib/terminal-workbench").WatchlistCacheRefreshItemRow) => void;
  selectWatchlistCacheRefreshRun: (row: import("../../../lib/terminal-workbench").WatchlistCacheRefreshHistoryRow) => void;
  selectTimeframe: (timeframe: import("../../../lib/terminal-workbench").Timeframe, targetWorkAreaId?: "market" | "research") => void;
  runAiWorkbenchAction: (action: import("../../../lib/terminal-workbench").AiWorkbenchAction) => void;
  updateStrategyRuleDraftField: (field: import("../../../lib/terminal-workbench").StrategyRuleDraftField, value: string | number | boolean) => void;
  applyStrategyTemplate: (templateId: import("../../../lib/terminal-workbench").StrategyTemplateId) => void;
  applyGeneratedStrategyDraft: (draft: import("../../../lib/terminal-workbench").StrategyRuleDraft, reasons: string[]) => void;
  saveCurrentStrategyVersion: () => Promise<void>;
  bindStrategyToProduction: (strategy: import("../../../pages/app-shell/initial-state").ProductionStrategyBindingTarget | null, operator: string) => Promise<boolean>;
  deleteSavedStrategyVersion: (strategy: import("../../../lib/strategy-transport").StrategyLibraryItem) => Promise<boolean>;
  saveCurrentResearchNote: () => Promise<void>;
  generateCurrentResearchNoteDraft: () => Promise<void>;
  selectResearchNoteProvider: (providerId: import("../../../lib/ai-review-stage3").AiReviewProviderId) => void;
  saveCurrentHandoffNote: () => Promise<void>;
  saveCurrentWatchlist: () => Promise<void>;
  removeWatchlistInstrument: (instrument: import("../../../lib/terminal-workbench").Instrument) => Promise<void>;
  saveCurrentResearchWorkspace: () => Promise<void>;
  loadSavedStrategyVersion: (strategy: import("../../../lib/strategy-transport").StrategyLibraryItem) => void;
  runStrategyGovernanceAction: (row: import("../../../lib/terminal-workbench").StrategyGovernanceQueueRow) => void;
  updateBacktestAssumption: (field: keyof import("../../../lib/terminal-workbench").BacktestAssumptions, value: number) => void;
  runStrategyExperiment: () => Promise<import("../../../lib/terminal-workbench").StrategyExperimentDetail | null>;
  inspectStrategyExperiment: (experimentId: string) => Promise<void>;
  replayStrategyExperiment: (experimentId: string) => Promise<void>;
  exportStrategyExperimentJson: (experiment: import("../../../lib/terminal-workbench").StrategyExperimentDetail) => void;
  loadStrategyExperimentCandidate: (candidateId: string) => Promise<void>;
  submitPaperExecution: (runIdOverride?: string | undefined) => Promise<void>;
  commitProductWorkAreaSelection: (areaId: import("../../../lib/terminal-workbench").ProductWorkAreaId) => void;
  selectProductWorkArea: (areaId: import("../../../lib/terminal-workbench").ProductWorkAreaId) => void;
  continueEditingSettings: () => void;
  saveSettingsAndLeave: () => void;
  discardSettingsAndLeave: () => void;
  openResearchPipelinePreflightIssue: (issue: import("../../../lib/terminal-workbench").ResearchPipelinePreflightIssue) => void;
  focusExecutionAdapterPaperExecutionAudit: (row: import("../../../lib/terminal-workbench").ExecutionAdapterPaperExecutionRow) => void;
  runPortfolioPaperOpsQueueAction: (row: import("../../../lib/terminal-workbench").PortfolioPaperOpsQueueRow) => void;
  focusExecutionAdapterPreLiveRunbookAudit: () => void;
  focusOperatorRunbookAudit: () => void;
  openP2ReadinessAcceptanceGeneratedAudit: () => void;
  openP2ReadinessAcceptanceReviewAudit: () => void;
  openP2ReadinessAcceptanceCoverageReviewAudit: () => void;
  openP2ReadinessEvidenceCoverageReviewAudit: () => void;
  openP2ReadinessEvidenceCoverageLinkedAcceptanceReviewAudit: () => void;
  openP2ManifestChainPreflightAudit: () => void;
  openP2ManifestChainPreflightReviewAudit: () => void;
  openP2ReadinessEvidenceCoverage: (row: import("../../../lib/terminal-workbench").P2ReadinessEvidenceCoverageRow) => void;
  openExecutionAdapterPaperExecutionEvidence: (row: import("../../../lib/terminal-workbench").ExecutionAdapterPaperExecutionAuditLedgerRow) => void;
  copyExecutionAdapterPaperExecutionEvidenceLink: (row: import("../../../lib/terminal-workbench").ExecutionAdapterPaperExecutionAuditLedgerRow) => Promise<void>;
  openMarketDataAdapterWorkflow: (adapter: import("../../../lib/platform-settings").PlatformSettingsMarketDataAdapter) => void;
  openAuditReportLedgerEvidenceLink: (search: string) => void;
  openAuditReportLedgerResearchContextLink: (search: string) => void;
  copyAuditReportLedgerEvidenceLink: (search: string) => Promise<void>;
  openLatestResearchContextReportInAudit: () => void;
  openLatestOtherResearchContextReportInAudit: () => void;
  openLatestResearchContextReportContext: () => void;
  copyLatestResearchContextReportLink: () => void;
  copyAuditReportLedgerQueryLink: (query: string) => Promise<void>;
  openAuditReportLedgerQuery: (query: string, statusLabel?: string) => void;
  copyExecutionAdapterPreLiveRunbookAuditLink: () => Promise<void>;
  copyOperatorRunbookAuditLink: () => Promise<void>;
  copyLatestOtherResearchContextReportAuditLink: () => Promise<void>;
  copyExecutionAdapterPaperExecutionAuditLink: (row: import("../../../lib/terminal-workbench").ExecutionAdapterPaperExecutionRow) => Promise<void>;
  copyP0CurrentGapActionLink: (search: string) => Promise<void>;
  copyP0CompletionGapLink: (targetWorkspaceId: import("../../../lib/terminal-workbench").ProductWorkAreaId | null | undefined, auditReportQuery: string) => Promise<void>;
  copyLocalReviewCoverageNextActionLink: (targetWorkspaceId: import("../../../lib/terminal-workbench").ProductWorkAreaId | null | undefined, auditReportQuery: string) => Promise<void>;
  openP0CurrentGapActionLink: (search: string) => void;
  copyP0ActionOutcomeEvidenceLink: (outcome: import("../../../lib/terminal-workbench").P0PlatformActionOutcome) => Promise<void>;
  copyP0ReadinessReport: () => Promise<void>;
  copyP0AcceptanceReview: () => Promise<void>;
  downloadP0AcceptanceReview: () => void;
  copyPersonalTeamReadinessReview: () => Promise<void>;
  downloadPersonalTeamReadinessReview: () => void;
  recordPersonalTeamReadinessReview: () => Promise<void>;
  openPersonalTeamReadinessReviewInAudit: () => void;
  copyPersonalTeamReadinessReviewAuditLink: () => void;
  openDailyOpsControlRoomReviewInAudit: () => void;
  copyDailyOpsControlRoomReviewAuditLink: () => void;
  copyDailyOpsControlRoomReview: () => Promise<void>;
  copyStage1P0DailyUseHandoff: () => Promise<void>;
  copyStage1P0DailyUsePrimaryLink: (copiedStatusLabel?: string) => Promise<void>;
  buildStage1P0ShareLinkBundleText: () => string;
  copyStage1P0ShareLinkBundle: () => Promise<void>;
  buildStage1P0InvalidShareDiagnosticsText: () => string;
  copyStage1P0InvalidShareDiagnostics: () => Promise<void>;
  buildStage1P0DailyUseArchiveBundle: () => Promise<import("../../../lib/terminal-workbench").Stage1P0DailyUseArchiveBundle>;
  copyStage1P0DailyUseArchive: () => Promise<void>;
  openStage1P0DailyUseRow: (row: import("../../../lib/terminal-workbench").Stage1P0DailyUseClosureRow) => void;
  openStage1P0DailyUsePrimaryAction: () => void;
  openStage1P0DailyUseRefreshOutcomeEntry: (entry: import("../../../lib/terminal-workbench").Stage1P0DailyUseRefreshOutcomeEntry) => void;
  openStage1P0DailyUseRefreshOutcomeNextStep: () => void;
  downloadStage1P0DailyUseHandoff: () => void;
  downloadStage1P0ShareLinkBundle: () => void;
  downloadStage1P0DailyUseArchive: () => Promise<void>;
  recordStage1P0DailyUseArchive: () => Promise<void>;
  openStage1P0DailyUseArchiveReviewInAudit: () => void;
  copyStage1P0DailyUseArchiveReviewAuditLink: () => void;
  copyStage1P0DailyUseArchiveReviewSummary: () => Promise<void>;
  downloadStage1P0DailyUseArchiveReviewSummary: () => void;
  copyStage1P0DailyUseStartupSnapshot: () => Promise<void>;
  downloadStage1P0DailyUseStartupSnapshot: () => void;
  copyStage1P0DailyUseRefreshOutcome: () => Promise<void>;
  copyStage1P0DailyUseRefreshOutcomeLink: () => Promise<void>;
  downloadStage1P0DailyUseRefreshOutcome: () => void;
  downloadDailyOpsControlRoomReview: () => void;
  recordDailyOpsControlRoomReview: () => Promise<void>;
  openDailyStartBriefReviewInAudit: () => void;
  copyDailyStartBriefReviewAuditLink: () => void;
  copyDailyStartBriefReview: () => Promise<void>;
  downloadDailyStartBriefReview: () => void;
  recordDailyStartBriefReview: () => Promise<void>;
  copyP2ReadinessAcceptanceReview: () => Promise<void>;
  downloadP2ReadinessAcceptanceReview: () => void;
  saveP2ReadinessAcceptanceReview: () => Promise<void>;
  copyP2ReadinessEvidenceCoverageReview: () => Promise<void>;
  downloadP2ReadinessEvidenceCoverageReview: () => void;
  saveP2ReadinessEvidenceCoverageReview: () => Promise<void>;
  copyP2ManifestChainPreflightReview: () => Promise<void>;
  downloadP2ManifestChainPreflightReview: () => void;
  saveP2ManifestChainPreflightReview: () => Promise<void>;
  saveP0AcceptanceReview: () => Promise<void>;
  downloadP0ReadinessReport: () => void;
  saveP0ReadinessReport: () => Promise<void>;
  focusLatestP0ReadinessReport: () => void;
  focusLatestP0PreparationEvidence: () => void;
  focusLatestP0Progress: () => void;
  focusLatestP0Preflight: () => void;
  focusLatestP0Completion: () => void;
  openLatestP0CompletionGap: () => void;
  focusLatestP0BacklogReadiness: () => void;
  focusLatestP0CurrentGapReadiness: () => void;
  focusPortfolioOrderStateAuditQuery: (query: string) => void;
  openP0ActionOutcomeEvidence: (outcome: import("../../../lib/terminal-workbench").P0PlatformActionOutcome) => void;
  inspectRefreshEvidenceRun: (runId: string) => void;
  openSelectedRefreshCoverageInResearch: () => void;
  submitSymbol: (event: React.FormEvent<HTMLFormElement>) => void;
  selectSearchSuggestion: (suggestion: import("../../../lib/market-exploration").MarketSearchSuggestion) => void;
  refreshSearchSuggestionCache: (suggestion: import("../../../lib/market-exploration").MarketSearchSuggestion) => Promise<void>;
  runActiveWorkflowAction: () => void;
  openLiveTradingGate: () => Promise<void>;
  completeLiveTradingGate: () => Promise<void>;
  runGoldenPathActionById: (actionId: string | null | undefined, targetWorkspace?: string | null | undefined, latestRunIdOverride?: string | null | undefined, automated?: boolean) => Promise<boolean>;
  runGoldenPathAction: () => void;
  runWorkspaceContextAction: () => void;
  isGoldenPathActionDisabledById: (actionId: string | null | undefined) => boolean;
  goldenPathActionId: string | undefined;
  isGoldenPathActionDisabled: boolean;
  workspaceContextActionId: string | null | undefined;
  isWorkspaceContextActionDisabled: boolean;
  goldenPathActionHint: string | null;
  workspaceContextActionHint: string | null;
  stopAutomatedTradingWorkflow: (message: string) => void;
  runAutomatedTradingWorkflow: () => void;
  runAutomatedTradingWorkflowFromCurrentWorkspace: () => void;
  renderChartPanel: (className?: string) => React.JSX.Element;
  renderStrategyWorkbench: (showSaveAction?: boolean) => React.JSX.Element;
  renderStrategyPanel: (className?: string) => React.JSX.Element;
  renderAgentPanel: (className?: string) => React.JSX.Element;
  renderWorkflowNodesPanel: (className?: string, title?: string, subtitle?: string) => React.JSX.Element;
  syncExecutionSafety: (executionMode: "paper" | "live" | "testnet", liveTradingAllowed: boolean) => void;
  executionLiveTradingAllowed: boolean;
  executionMode: "paper" | "live" | "testnet";
  executionTestnetKillSwitch: import("../../../lib/stage6-sandbox").Stage6KillSwitch | null;
  executionReadinessStack: React.JSX.Element;
  executionAcceptanceAuditPanel: React.JSX.Element;
  canPrepareTerminalAiReview: boolean;
  canRunTerminalAiReview: boolean;
  aiReviewNeedsExternalApproval: boolean;
  aiReviewActionLabel: "AI 评审运行中…" | "正在加载评审…" | "请先完成研究运行" | "请先完善实验参数" | "请先授权已完成 K 线与证据" | "运行 AI 评审" | "AI 评审暂不可用";
  runTerminalAiReview: () => Promise<void>;
  openAutomaticTradingConsole: () => void;
  terminalSurfaceAction: import("../../../components/TerminalSurfaceUi").SurfaceAction | null;
  terminalSurfaceDisplayAction: import("../../../components/TerminalSurfaceUi").SurfaceAction | null;
  automatedTradingGuideAction: () => void;
  automatedTradingGuide: React.JSX.Element;
  colorSchemeToggleLabel: "切换到浅色模式" | "切换到深色模式" | "Switch to light mode" | "Switch to dark mode";
  textScalePercent: number;
  footerExecutionSafety: { liveTradingAllowed: boolean; requiredGates: string[]; executionMode?: "paper" | "live" | "testnet" | undefined; liveConfirmed?: boolean | undefined; liveSessionTtlHours?: number | undefined; liveAuthorizedUntil?: string | null | undefined; productionLive?: { enabled: boolean; credentialsConfigured: boolean; controlActive: boolean; controlRecordedActive: boolean; evidenceFresh: boolean; blockingReason: string | null; triggered: boolean; } | undefined; } | undefined;
  authoritativeFooterSnapshotExpected: boolean;
  footerExecutionStateAvailable: boolean;
  currentExecutionMode: "paper" | "live" | "testnet" | undefined;
  footerLiveTradingAllowed: boolean;
  currentExecutionModeLabel: "Paper simulation" | "状态读取中" | "Loading" | "生产实盘" | "Production live" | "生产实盘受保护" | "Production live protected" | "币安测试网" | "Binance Testnet" | "纸面模拟";
  currentExecutionVenueLabel: "币安测试网" | "Binance Testnet" | "币安现货" | "Binance Spot" | "纸面经纪" | "Paper Broker";
  currentExecutionTone: "blocked" | "paper" | "live";
  currentLiveBadgeLabel: "权限读取中" | "Loading permissions" | "生产会话有效" | "Production session active" | "生产闸门保护中" | "Production gate protected" | "实盘需授权" | "Live authorization required";
  footerExecutionStatus: "未加载" | "Unavailable" | "已授权" | "Authorized" | "Testnet" | "Paper" | "未授权" | "Not authorized";
  footerExecutionDetail: "生产会话有效" | "Production session active" | "正在读取执行状态" | "Loading execution status" | "生产权限证据已过期" | "Production permission evidence expired" | "生产交易凭据未配置" | "Production credentials missing" | "生产会话未开启，切换时需实名确认" | "Production session inactive; named confirmation required";
  changeLocale: (locale: import("../../../lib/i18n").Locale) => void;
  changeTextScale: (scale: number) => void;
  toggleColorScheme: () => void;
  changeMarketDraft: (market: import("../../../lib/terminal-workbench").Market) => void;
  changeSymbolDraft: (symbol: string) => void;
  openSymbolSearch: () => void;
  updateAutoTradingSnapshot: (snapshot: import("../../../pages/shared/auto-trading-contract").AutoTradingSnapshot | null) => void;
  closeLiveTradingGate: () => void;
  closeExpandedChart: () => void;
  dismissResearchCompletionNotice: () => void;
  closeResearchPipelinePreflight: () => void;
  reportAiReviewContextError: (message: string) => void;
  updateSettingsConfigurationDirty: (dirty: boolean) => void;
  approveResearchNoteExternalData: (approved: boolean) => void;
}
